#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include <stdbool.h>

#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

#include "types.h"

// The SWIG external runtime is generated by using.
// swig -lua -external-runtime swig_runtime.h
#include "swig_runtime.h"

extern int luaopen_bindings(lua_State *L);

void callProcessStruct(lua_State *L, my_struct_t *my_struct)
{
    lua_getglobal(L, "processStruct");
    assert(lua_isfunction(L, -1));

    swig_type_info *type = SWIG_TypeQuery(L, "my_struct_t *");
    assert(type != NULL);
    SWIG_NewPointerObj(L, my_struct, type, false);

    // Call function with 1 arguments and no result
    assert(lua_pcall(L, 1, 0, 0) == LUA_OK);
}

int main(void)
{
    lua_State *L = luaL_newstate();
    assert(L != NULL);

    luaL_openlibs(L);
    luaopen_bindings(L); // Load the wrapped module

    int r = luaL_loadfile(L, "example4.lua");
    assert(r == LUA_OK);

    printf("[C] Loading script\r\n");

    // Load the script by calling it
    assert(lua_pcall(L, 0, 0, 0) == LUA_OK);

    my_struct_t my_struct;
    static const uint32_t prioritiesCount = sizeof(my_struct.priorities)/sizeof(my_struct.priorities[0]);

    for (uint32_t i = 0; i < prioritiesCount; i++)
    {
        my_struct.priorities[i] = 1;
    }

    printf("[C] Calling processStruct\r\n");
    callProcessStruct(L, &my_struct);
    printf("[C] We're back from Lua\r\n");

    printf("[C] Printing my_struct.priorities\r\n");
    for (uint32_t i = 0; i < prioritiesCount; i++)
    {
        printf("\tpriorities[%d] = %d\r\n", i, my_struct.priorities[i]);
    }

    lua_close(L);
    printf("[C] Finished\r\n");
}
