[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32U585AIIx"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "trace"

[profile.release]
# Allows defmt to display log locations even in release
debug = true
