name: Detect Ruby Version Mismatch
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - 'readme.md'
      - '.ruby-version'

jobs:
  check_ruby_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Verify Ruby version in readme.md matches .ruby-version
        run: |
          RUBY_VERSION=$(cat .ruby-version)
          grep -- "- Ruby $RUBY_VERSION" readme.md
